# =========================
# OSC Near-RT RIC values
# =========================

# E2 termination — port SCTP pour les gNBs
e2term:
  image:
    repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2
    tag: 5.5.0
    # 6.0.0 segfaults; 5.5.0 works with SCTP loaded
    pullPolicy: IfNotPresent
  port:
    sctp: 36421
    http: 8088

# E2 Manager
e2mgr:
  image:
    repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2mgr
    tag: 5.5.0
    pullPolicy: IfNotPresent
  port:
    http: 3800

# Routing Manager
rtmgr:
  image:
    repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-rtmgr
    tag: 0.9.7
    pullPolicy: IfNotPresent
  port:
    http: 4561

# Subscription Manager
submgr:
  image:
    repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-submgr
    tag: 0.9.5
    pullPolicy: IfNotPresent
  port:
    http: 8088

# Application Manager
appmgr:
  image:
    repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-appmgr
    tag: 0.5.6
    pullPolicy: IfNotPresent
  port:
    http: 8080

# Redis — base de données partagée entre les composants RIC
redis:
  image:
    repository: redis
    tag: "6.2"
    pullPolicy: IfNotPresent
  port: 6379

# IP du RIC exposée aux gNBs (à adapter selon le cluster)
ricIp: 10.10.3.210
