image:
  repository: ghcr.io/salimkarroum/channel-emulator
  tag: v1.0
  pullPolicy: IfNotPresent

gnb:
  zmqTxAddr: "tcp://srsran-gnb:2000"
  zmqRxBind: "tcp://0.0.0.0:2001"

ue:
  zmqTxAddr: "tcp://srsue:2101"
  zmqRxBind: "tcp://0.0.0.0:2100"

channel:
  distanceMinKm: "0.5"
  distanceMaxKm: "2.0"
  dopplerMaxHz: "50"
  noiseFigureDb: "7"
