# =========================
# gNB values file for ZMQ setup.
# =========================

image:
  repository: ghcr.io/salimkarroum/srsran-gnb-zmq
  tag: v1.0
  pullPolicy: IfNotPresent

resources:
  define: false
  requests:
    cpu: "50m"
    memory: "3000Mi"
  limits:
    cpu: "5000m"
    memory: "3000Mi"

start:
  gnb: true
  logs: true

gnbIp: 10.10.3.231

gnbConfig:
  cu_cp:
    inactivity_timer: 7200
    request_pdu_session_timeout: 30
    amf:
      addr: 10.10.3.200
      port: 38412
      bind_addr: 10.10.3.231
      supported_tracking_areas:
        - tac: 1
          plmn_list:
            - plmn: "00101"
              tai_slice_support_list:
                - sst: 1
                - sst: 1
                  sd: "000002"

  ru_sdr:
    device_driver: zmq
    device_args: >-
      tx_port=tcp://10.10.3.231:2000,rx_port=tcp://10.10.3.232:2001,base_srate=23.04e6
    srate: 23.04
    tx_gain: 75
    rx_gain: 75

  cell_cfg:
    dl_arfcn: 368500
    band: 3
    channel_bandwidth_MHz: 20
    common_scs: 15
    plmn: "00101"
    tac: 1
    pdcch:
      common:
        ss0_index: 0
        coreset0_index: 12
      dedicated:
        ss2_type: common
        dci_format_0_1_and_1_1: false
    prach:
      prach_config_index: 1
    pdsch:
      mcs_table: qam64
    pusch:
      mcs_table: qam64
    slicing:
      - sst: 1
      - sst: 1
        sd: "000002"

  log:
    filename: /var/log/gnb.log
    all_level: warning
    config_level: debug

  metrics:
    enable_log: false
    autostart_stdout_metrics: true
    enable_json: true
    layers:
      enable_app_usage: true
      enable_e1ap: true
      enable_pdcp: true
      enable_sched: true
      enable_rlc: true
      enable_mac: true
      enable_executor: true
      enable_du_low: true
      enable_ru: true

  pcap:
    mac_enable: false
    mac_filename: /tmp/gnb_mac.pcap
    ngap_enable: false
    ngap_filename: /tmp/gnb_ngap.pcap

  remote_control:
    bind_addr: 0.0.0.0
    enabled: true
    port: 8001
