apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rl-xapp.fullname" . }}-kpm-code
  labels:
    {{- include "rl-xapp.labels" . | nindent 4 }}
data:
  kpm_adapter.py: |
{{ .Files.Get "files/kpm_adapter.py" | indent 4 }}
