apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srsdu.fullname" . }}
  labels:
    {{- include "srsdu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "srsdu.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "srsdu.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "n3network", "interface": "n3", "ips": [ "{{ .Values.duIp }}/24" ] }]'
    spec:
      containers:
        - name: du
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          {{- if .Values.start.du }}
            - /usr/local/bin/srsdu -c /srsran/config/srsdu.yaml
          {{- else }}
            - sleep infinity
          {{- end }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /mnt/*_log.txt"]
          volumeMounts:
            - mountPath: /srsran/config
              name: du-volume
            - mountPath: /var/log/
              name: varlog
            - name: host-mount
              mountPath: /mnt/
          {{- if .Values.resources.define}}
          resources:
            requests:
              memory: {{ .Values.resources.requests.tcpdump.memory | quote }}
              cpu: {{ .Values.resources.requests.tcpdump.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.tcpdump.memory | quote }}
              cpu: {{ .Values.resources.limits.tcpdump.cpu | quote }}
          {{- end}}
      {{- if .Values.start.logs }}
        - name: du-logs
          image: busybox
          args: [/bin/sh, -c, 'while ! tail -f /var/log/du.log 2>/dev/null; do sleep 1 ; done']
          volumeMounts:
            - mountPath: /var/log/
              name: varlog
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: du-volume
          configMap:
            name: du-configmap
            items:
              - key: srsdu.yaml
                path: srsdu.yaml
        - name: varlog
          emptyDir: {}
        - name: host-mount
          hostPath:
            path: /mnt/
            type: Directory
